baseURL = 'https://hadron-sclang.org/'
languageCode = 'en-us'
title = 'Hadron SuperCollider Language'
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true
enableGitInfo = true

# Required if you want to render robots.txt template
enableRobotsTXT = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    # Needed for mermaid shortcode
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9

[taxonomies]
  tag = "tags"

[params]
  geekdocRepo = "https://github.com/hadron-sclang/hadron-sclang.org"
  geekdocEditPath = "edit/main"

